### ISSUE TITLE
Refactor to use ObjectCreated instead of direct subscription

### ISSUE THREAD

**Issue by pathunstrom** [pathunstrom/pursuedpybear#34]
See the __init__ of physics.Physics for pattern.

**Comment by dillonko** [comment]
Hey Piper
I realized I don't have your email. what is it? also Is it ok if I use
pyglet for creating the test characters(sprites)? hopfully I will hear from
you soon.

best,
Dillon

**Comment by pathunstrom** [comment]
@dillonko 

https://github.com/pathunstrom/pursuedpybear/blob/master/CONTRIBUTORS.md <- It's in here.

If you're doing more than just samples, you'll need to make a pyglet wrapper in ext (The pattern should be obvious, but email me or open a ticket if you'd like help in what's necessary.)
